version: "3.8"

services:
  order:
    container_name: order
    restart: always
    build:
      context: ./
      dockerfile: ../apps/order/Dockerfile
    volumes:
      - /opt/app/node_modules
      - ../dist/apps/order:/opt/app/dist
    env_file:
      - ../envs/.mongo.env
      - ../envs/.nats.env
      - ../envs/.redis.env
      - ../envs/.jwt.env
      - ../envs/.order.env
    command: npm run start:prod
    depends_on:
      - nats
      - mongo
      - redis
    networks:
      - tngmn

  order-prod:
    container_name: order-prod
    restart: always
    build:
      context: ./
      dockerfile: ../apps/order/Dockerfile
    volumes:
      - /opt/app/node_modules
    env_file:
      - ../envs/.mongo.env
      - ../envs/.nats.env
      - ../envs/.redis.env
      - ../envs/.jwt.env
      - ../envs/.order.env
    command: npm run start:prod
    depends_on:
      - nats
      - mongo
      - redis
    networks:
      - tngmn

networks:
  tngmn:
    driver: bridge
