version: "3.8"

services:
  nats:
    image: nats
    container_name: nats
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    expose:
      - "4222"
    restart: always
    networks:
      - tngmn

networks:
  tngmn:
    driver: bridge
  
