version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - tngmndata:/data/db
    ports:
      - '27017:27017'
    networks:
      - tngmn

  mongo-prod:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - tngmndata:/data/db
    expose:
      - '27017'
    networks:
      - tngmn

networks:
  tngmn:
    driver: bridge

volumes:
  tngmndata:

