FROM node:16-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/app

ADD package*.json ./
ADD schema.gql ./schema.gql

RUN npm install glob rimraf
RUN npm install 

COPY . .

RUN npm run start:dev api


